collection: COLLECTION

# SQS config
queue_url: http://localhost:9324/000000000000/queue1
batch_size: 10
wait_time_seconds: 10

delete_workers: 5
max_source_workers: 4
max_feed_workers: 10
max_delete_workers: 2
per_message_interval: 100ms

script_path: bin/work.sh
stdout_path: /tmp/work.out
stderr_path: /tmp/work.err
